=== BioGearsEngine/Engine/lib/xsd-4.0.0-x86_64-linux-gnu/examples/cxx/tree/embedded/library.xsd
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/embedded/library.xsd
copyright : not copyrighted - public domain

-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xse="http://www.codesynthesis.com/xmlns/xml-schema-extension"
            xmlns:lib="http://www.codesynthesis.com/library"
            targetNamespace="http://www.codesynthesis.com/library">

  <xsd:simpleType name="isbn">
    <xsd:restriction base="xsd:unsignedInt"/>
  </xsd:simpleType>

  <xsd:complexType name="title">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="lang" type="xsd:language"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="genre">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="romance"/>
      <xsd:enumeration value="fiction"/>
      <xsd:enumeration value="horror"/>
      <xsd:enumeration value="history"/>
      <xsd:enumeration value="philosophy"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="person">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="born" type="xsd:date"/>
      <xsd:element name="died" type="xsd:date" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="author">
    <xsd:complexContent>
      <xsd:extension base="lib:person">
	<xsd:attribute name="recommends" type="xsd:IDREF" xse:refType="lib:book"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="book">
    <xsd:sequence>
      <xsd:element name="isbn" type="lib:isbn"/>
      <xsd:element name="title" type="lib:title"/>
      <xsd:element name="genre" type="lib:genre"/>
      <xsd:element name="author" type="lib:author" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="available" type="xsd:boolean" default="true"/>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="catalog">
    <xsd:sequence>
      <xsd:element name="book" type="lib:book" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="catalog" type="lib:catalog"/>

</xsd:schema>

=== BioGearsEngine/Engine/lib/xsd-4.0.0-i686-macosx/examples/cxx/tree/library/library.xml
<?xml version="1.0"?>

<!--

file      : examples/cxx/tree/library/library.xml
copyright : not copyrighted - public domain

-->

<lib:catalog xmlns:lib="http://www.codesynthesis.com/library"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:schemaLocation="http://www.codesynthesis.com/library library.xsd">

  <book id="MM" available="false">
    <isbn>0679760806</isbn>
    <title>The Master and Margarita</title>
    <genre>fiction</genre>

    <author recommends="WP">
      <name>Mikhail Bulgakov</name>
      <born>1891-05-15</born>
      <died>1940-03-10</died>
    </author>
  </book>


  <book id="WP">
    <isbn>0679600841</isbn>
    <title>War and Peace</title>
    <genre>history</genre>

    <author recommends="CP">
      <name>Leo Tolstoy</name>
      <born>1828-09-09</born>
      <died>1910-11-20</died>
    </author>
  </book>


  <book id="CP" available="false">
    <isbn>0679420290</isbn>
    <title>Crime and Punishment</title>
    <genre>philosophy</genre>

    <author>
      <name>Fyodor Dostoevsky</name>
      <born>1821-11-11</born>
      <died>1881-02-09</died>
    </author>
  </book>

</lib:catalog>
